project:
  type: book
  output-dir: docs

book:
  title: "Project Euler with R, Julia and Python"
  author: "??????"
  date: "13/06/2023"
  chapters:
    - index.qmd
    - p1_10.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 1
  # pdf:
  #   documentclass: scrreprt
